Initial version of the hundred acre wood activity
AdaGold/hundred-acre-wood pull request #1
Opened 2018-09-04 20:55 UTC by dHelmgren

The general idea is to give the students a quick taste of how to use file paths, without bogging them down with writing other code. Its very quick to complete, with automated feedback.

2018-09-10 18:48 UTC, droberts-sea requested changes

2018-09-10 18:48 UTC, droberts-sea commented on README.md
> +The only file you should be editing is `lets_find-eyores-tail.rb`. You are going to fill in the string declarations at the top of the file. Each of those paths will lead to a file that ends in `.txt`
It is not obvious to me as a pretend student where this file is or where my terminal should be as I work on this. I would love explicit setup instructions:

```
$ git clone ...
$ cd hundred-acre-wood/Six-Pines
$ ruby lets-find-eyores-tail.rb
```

It also might be good to walk through finding the first file here in the README.

2018-09-10 18:48 UTC, droberts-ada commented on README.md
> +Enter hidden files and folders! In iOS, any file or folder whose name begins with a `.` is hidden when using the Finder app. They are visible to programs like Atom, but end users don't see them unles
I might add a note that this doesn't deny anyone access, but it does prevent users from fiddling with things by mistake.

2018-09-10 18:48 UTC, droberts-ada commented on README.md
It might be good to include a disclaimer that, while Winnie the Pooh is lovely and fantastic, you don't need to be familiar with the stories to do this exercise.

2018-09-10 18:48 UTC, droberts-ada commented on Six-Pines/lets-find-eyores-tail.rb
> +end
Could you make this a little more interactive? Right now it just returns `ENOENT` if any of the 4 file names aren't filled in correctly, which doesn't give a lot of hint as to what should be done.

Maybe instead it could be something like this:

```
Eyore has lost his tail again. Oh bother!
Let's ask around - perhaps someone has seen it.

Maybe Kanga knows where Eyore's tail is.
Kanga's address is:
../Kanga-And-Roos-House/kanga.txt
let's go see if they know!
[... ASCII art...]
"Sorry, but I do not know where Eyore's tail is."

Maybe Piglet knows where Eyore's tail is.
We don't know what Piglet's address is. Fill it in at the top of the file so we can continue!
```

2018-09-10 18:48 UTC, droberts-ada commented on Six-Pines/lets-find-eyores-tail.rb
> +who_was_asked = [kanga_roo_address, piglet_address, rabbit_address, pooh_address]
Would it make sense to store these in a hash?

2018-09-10 18:48 UTC, droberts-ada commented on README.md
> +You have fallen into the Heffalump Trap. There are two folders in this project called Heffalump-Trap, and one is hidden when you use finder. If you need more information, read about hidden files and
I only see one Heffalump Trap.

2018-09-10 21:56 UTC, Hamled commented on README.md
> +You have fallen into the Heffalump Trap. There are two folders in this project called Heffalump-Trap, and one is hidden when you use finder. If you need more information, read about hidden files and
@dHelmgren If one of those Heffalump Trap folders was empty (the non-hidden one, presumably), then Git probably ignored it because it has no way of tracking empty directories. You can create an add an empty `.keep` file in there if you want to ensure the directory is included in the repo.

2018-09-10 22:10 UTC, Hamled requested changes
I agree with Dan's comments, in particular about expanding the setup instructions and making the Ruby script more friendly when things aren't working.

I've only got suggested text/wording changes, no changes to the actual exercise content.

2018-09-10 22:10 UTC, Hamled commented on README.md
> +The only file you should be editing is `lets_find-eyores-tail.rb`. You are going to fill in the string declarations at the top of the file. Each of those paths will lead to a file that ends in `.txt`
`lets_find-eyores-tail.rb` -> `lets-find-eyores-tail.rb`

2018-09-10 22:10 UTC, Hamled commented on README.md
> +Sometimes, there are files or folders that you want to include in a project that you don't necessarily want any old user to mess with. Since your application is running on someone else's computer tho
"your customers" -> "your users"

2018-09-10 22:10 UTC, Hamled commented on README.md
> +Enter hidden files and folders! In iOS, any file or folder whose name begins with a `.` is hidden when using the Finder app. They are visible to programs like Atom, but end users don't see them unles
iOS -> macOS

2018-09-10 22:10 UTC, Hamled commented on README.md
> +Most systems have been switched out of ASCII, because ASCII is suited exclusively to English. Unicode has created a successor, or rather, a set of successors: UTF-8, UTF-16 and UTF-32. UTF stands for
Replacement for final sentence:
UTF stands for Unicode Transformation Format, and the number following represents the minimum number of bits that the encoding needs per character.

2018-09-13 16:14 UTC, dHelmgren commented on Six-Pines/lets-find-eyores-tail.rb
> +end
I was worried this was going to be too cheesy, but I can do that. :)

2018-09-13 16:41 UTC, dHelmgren commented on README.md
Check

2018-09-13 17:24 UTC, CheezItMan requested changes
Mostly I just agree with Dan's feedback, giving the user a more readable message rather than the stack trace when the path is wrong would be better.  

This should be good practice.

2018-09-13 17:24 UTC, CheezItMan commented on .gitignore
> +/Six-Pines/lets-find-eyores-tail-solution.rb
I would also add:

.DS_Store

2018-09-14 16:30 UTC, Hamled approved these changes

2018-09-14 17:14 UTC, droberts-sea approved these changes
I think this will do splendidly. Good work!

2018-09-14 17:15 UTC, merged